# Generated by Django 2.1.3 on 2018-11-27 07:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('section_blocks', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.TextBlock()), ('heading', wagtail.core.blocks.TextBlock()), ('content', wagtail.core.blocks.RichTextBlock()), ('link', wagtail.core.blocks.URLBlock(required=False))]))], blank=True, null=True, verbose_name='Page Body'),
        ),
    ]
