# Generated by Django 2.1.3 on 2018-11-28 07:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
                ('image', models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000px and 3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('description', wagtail.core.fields.StreamField([('section_blocks', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.TextBlock()), ('heading', wagtail.core.blocks.TextBlock()), ('content', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.TextBlock(required=False))])), ('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('icon', wagtail.core.blocks.TextBlock())])), ('project_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('summary', wagtail.core.blocks.TextBlock())])), ('paragraph', wagtail.core.blocks.RichTextBlock())], verbose_name='description')),
                ('links', wagtail.core.fields.StreamField([('section_blocks', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.TextBlock()), ('heading', wagtail.core.blocks.TextBlock()), ('content', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.TextBlock(required=False))])), ('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('icon', wagtail.core.blocks.TextBlock())])), ('project_link', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.URLBlock()), ('summary', wagtail.core.blocks.TextBlock())])), ('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True, null=True, verbose_name='links')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
